/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in full Next apps.
// It is checked in now so TypeScript tooling is ready during the migration.
